name: Release
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Zip Release
      run: zip -r release.zip Resources

    - name: Create Release
      uses: ncipollo/release-action@v1.6.1
      with:
        artifacts: release.zip
        body: Dnn Language pack
        tag: 1.2.3
        # The Github token.
        token: ${{ secrets.GITHUB_TOKEN }}
